baseURL = 'https://cybergirl876.github.io/'
locale = 'en-us'
title = 'The Signal Log'
theme = 'ananke'
publishDir = "docs"

[params]
  [params.ananke]
    custom_css = ["css/kkt2w-signal-log-theme.css"]